name = "Iuppiter-2"
author = "Losenone, Filostorm"
version = "0.9.3-r2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89b8320c1b6f0e7f1efc139689d29762d3d9f5840828a70b0c2ed27ec33f24cd"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
